name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # - hydra-core=1.3.2
  # - matplotlib=3.8.2
  # - pandas=2.1.3
  - pip
  - jupyter 
  # - scikit-learn=1.3.2
  - pip:
      - mlflow
      - wandb
      - hydra-core
      - matplotlib
      - pandas
      - ydata-profiling
      - scikit-learn
